// src/data/services.js
export const services = [
    { name: "Glow Sign & LED Board Fire Exit Radium Sign", image: "/assets/Glow Sign & LED.png", id: "glow-sign-led" },
    { name: "Outdoor Wall Graphic", image: "/assets/Outdoor Wall Graphic.png", id: "outdoor-wall-graphic" },
    { name: "Dugout Branding", image: "/assets/Dugout Branding.png", id: "dugout-branding" },
    { name: "Office Wall Graphic", image: "/assets/Office Wall Graphic.png", id: "office-wall-graphic" },
    { name: "Reflective Direction Signs", image: "/assets/Reflective Direction Signs.png", id: "reflective-direction-signs" },
    { name: "Pole Kiosk", image: "/assets/Pole Kiosk.png", id: "pole-kiosk" },
    { name: "Fleet Graphics", image: "/assets/Fleet Graphics.png", id: "fleet-graphics" },
    { name: "Thermocol Letter Cutout", image: "/assets/Thermocol letter cutout.png", id: "thermocol-letter-cutout" },
    { name: "Car Wrapping", image: "/assets/Car Wrapping.png", id: "car-wrapping" },
    { name: "Backlit Signages", image: "/assets/Backlit Signages.png", id: "backlit-signages" },
    { name: "Free Standing Units", image: "/assets/Free Standing Units.png", id: "free-standing-units" },
    { name: "Boundary Rope", image: "/assets/Boundary Rope.png", id: "boundary-rope" },
    { name: "Promotional Folding Kiosk", image: "/assets/Promotional Folding Kiosk.png", id: "promotional-folding-kiosk" },
    { name: "Mall Facia Branding", image: "/assets/Mall Facia Branding.png", id: "mall-facia-branding" },
    { name: "T-Shirt Printing (Sublimation)", image: "/assets/T-Shirt Printing.png", id: "t-shirt-printing" },
    { name: "Acrylic Dispensers", image: "/assets/Acrylic Dispensers.png", id: "acrylic-dispensers" },
    { name: "Event Backdrop", image: "/assets/Event Backdrop.png", id: "event-backdrop" },
    { name: "Vinyl Wrap on Cars", image: "/assets/Vinyl Wrap on Cars.png", id: "vinyl-wrap-cars" },
    { name: "Promotion Table with Umbrella", image: "/assets/Promotion Table.png", id: "promotion-table-umbrella" },
    { name: "In-store Branding", image: "/assets/In-store Branding.png", id: "in-store-branding" },
    { name: "Customized Bags", image: "/assets/Customized Bags.png", id: "customized-bags" },
    { name: "Novelties", image: "/assets/Novelties.png", id: "novelties" },
    { name: "Promotion Standee & Kiosk", image: "/assets/Promotion Standee & Kiosk.png", id: "promotion-standee-kiosk" },
    { name: "Frosted print on glass door and partition", image: "/assets/image.png", id: "frosted-glass-print" },
  ];